FROM nginx:alpine
COPY default.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/index.html
COPY dashboard.html /usr/share/nginx/html/dashboard.html
COPY 404.html /usr/share/nginx/html/404.html
COPY static/ /usr/share/nginx/html/static/
COPY llms.txt /usr/share/nginx/html/llms.txt
