ALTER TABLE users ALTER COLUMN active TYPE BOOLEAN USING (active != 0);
ALTER TABLE users ALTER COLUMN active SET DEFAULT true;

ALTER TABLE users ALTER COLUMN admin TYPE BOOLEAN USING (admin != 0);
ALTER TABLE users ALTER COLUMN admin SET DEFAULT false;
